// SSD1306 SPI OLED test sketch
// Displays a static bitmap image + a text message
// Wiring (hardware SPI, Arduino Uno/Nano):
//   OLED D0/SCK  -> Pin 13
//   OLED D1/MOSI -> Pin 11
//   OLED RES     -> Pin 9
//   OLED DC      -> Pin 8
//   OLED CS      -> Pin 10
//   OLED VCC     -> 3.3V or 5V (check your module's rating)
//   OLED GND     -> GND
//
// Requires: Adafruit_GFX and Adafruit_SSD1306 libraries
// (Sketch > Include Library > Manage Libraries, search each name)

#include <SPI.h>
#include <Adafruit_GFX.h>
#include <Adafruit_SSD1306.h>

#define SCREEN_WIDTH  128
#define SCREEN_HEIGHT 64

#define OLED_MOSI  11
#define OLED_CLK   13
#define OLED_DC    8
#define OLED_CS    10
#define OLED_RESET 9

Adafruit_SSD1306 display(SCREEN_WIDTH, SCREEN_HEIGHT,
                          OLED_MOSI, OLED_CLK, OLED_DC, OLED_RESET, OLED_CS);

// 32x32 pixel bitmap, 1-bit-per-pixel, MSB-first (a simple heart icon)
// Generated by hand as an example — swap in your own via image2cpp.com
static const unsigned char PROGMEM heart_bmp[] = {
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x03, 0x80, 0x0E, 0x00, 0x07, 0xC0, 0x1F, 0x00,
  0x0F, 0xE0, 0x3F, 0x80, 0x1F, 0xF8, 0xFF, 0xC0,
  0x3F, 0xFF, 0xFF, 0xE0, 0x7F, 0xFF, 0xFF, 0xF0,
  0x7F, 0xFF, 0xFF, 0xF0, 0xFF, 0xFF, 0xFF, 0xF8,
  0xFF, 0xFF, 0xFF, 0xF8, 0xFF, 0xFF, 0xFF, 0xF8,
  0x7F, 0xFF, 0xFF, 0xF0, 0x7F, 0xFF, 0xFF, 0xF0,
  0x3F, 0xFF, 0xFF, 0xE0, 0x1F, 0xFF, 0xFF, 0xC0,
  0x0F, 0xFF, 0xFF, 0x80, 0x07, 0xFF, 0xFF, 0x00,
  0x03, 0xFF, 0xFE, 0x00, 0x01, 0xFF, 0xFC, 0x00,
  0x00, 0xFF, 0xF8, 0x00, 0x00, 0x7F, 0xF0, 0x00,
  0x00, 0x3F, 0xE0, 0x00, 0x00, 0x1F, 0xC0, 0x00,
  0x00, 0x0F, 0x80, 0x00, 0x00, 0x07, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
};
#define HEART_W 32
#define HEART_H 32

void setup() {
  Serial.begin(9600);

  if (!display.begin(SSD1306_SWITCHCAPVCC)) {
    Serial.println(F("SSD1306 init failed - check wiring"));
    while (true);
  }

  display.clearDisplay();

  // Draw the bitmap on the left side, vertically centered
  display.drawBitmap((SCREEN_HEIGHT - HEART_H) / 2, (SCREEN_HEIGHT - HEART_H) / 2,
                      heart_bmp, HEART_W, HEART_H, SSD1306_WHITE);

  // Draw a text message to the right of the image
  display.setTextSize(1);
  display.setTextColor(SSD1306_WHITE);
  display.setCursor(72, 20);
  display.println(F("SSD1306"));
  display.setCursor(72, 32);
  display.println(F("SPI OK!"));

  display.display();
}

void loop() {
  // static test screen - nothing to update
}
